name: Plan and deploy infrastructure

on:
  workflow_call:
    inputs:
      module-path:
        required: true
        type: string
      s3-cache-bucket:
        required: true
        type: string
      region:
        required: false
        type: string
        default: us-east-1
      apply-environment:
        required: false
        type: string
        default: manual-approval
      node-version:
        required: false
        type: string
        default: 16
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ENV_VARS:
        required: false

env:
  TF_RECREATE_MISSING_LAMBDA_PACKAGE: false

jobs:
  plan:
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ${{ inputs.module-path }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure dynamic environment variables
        run: |-
          echo -e "${{ secrets.ENV_VARS }}" | while read LINE ; do
            SPLIT=(${LINE//=/ })
            VALUE=${SPLIT[1]}
            echo "::add-mask::$VALUE"
          done ;
          echo -e "${{ secrets.ENV_VARS }}" >> $GITHUB_ENV

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -input=false -backend-config=../backend.conf

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode -out tfplan.out

      - name: Upload build plan and outputs to S3
        run: |
          mkdir -p builds/
          aws s3 cp tfplan.out s3://${{ inputs.s3-cache-bucket }}/${{ github.run_id }}/tfplan.out
          aws s3 cp builds/ s3://${{ inputs.s3-cache-bucket }}/${{ github.run_id }}/builds/ --recursive

    outputs:
      planExitcode: ${{ steps.plan.outputs.exitcode }}

  apply:
    needs: [plan]
    if: always() && needs.plan.result == 'success' && needs.plan.outputs.planExitcode == 2
    environment: ${{ inputs.apply-environment }}
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ${{ inputs.module-path }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        run: terraform init -input=false -backend-config=../backend.conf

      - name: Download build plan and outputs from S3
        run: |
          aws s3 cp s3://${{ inputs.s3-cache-bucket }}/${{ github.run_id }}/tfplan.out tfplan.out
          aws s3 cp s3://${{ inputs.s3-cache-bucket }}/${{ github.run_id }}/builds/ builds/ --recursive

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve "tfplan.out"
